[build]
    base = "./"
    publish = "build/"
    command = "npm run build"
    # CI set to false until we fix all build warnings
    environment = { NODE_VERSION = "16", CI = "false" }

[[redirects]]
    from = "https://superlative-fenglisu-972af1.netlify.app"
    to = "https://www.refound.media"
    status = 301
    force = true
    query = {path = ":path"}